### ISSUE TITLE
./node_modules/.bin/rollup: not found

### ISSUE THREAD

**Issue by Zaid-maker** [TheRealToxicDev/GitHub-Updates-Bot#1]
i have deployed the app to heroku and set the tokens and everything but it's giving this error.

![image](https://user-images.githubusercontent.com/53424436/179475637-b9245d73-27d2-482c-a93d-f5d06cfccb1f.png)

**Comment by CodeMeAPixel** [comment]
I have updated the package. Please make sure you run the build script first 👌🏻

**Comment by Zaid-maker** [comment]
Thnx man

**Comment by CodeMeAPixel** [comment]
> Thnx man

No problem. You coulda fixed it yourself honestly node just doesn’t like you trying to run two scripts together anymore

**Comment by CodeMeAPixel** [comment]
Should be solved ❤️
